/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspectRouteImport } from './routes/inspect'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectRoute = InspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspect': typeof InspectRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspect': typeof InspectRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspect': typeof InspectRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inspect' | '/api/chat' | '/api/public/mcp' | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inspect' | '/api/chat' | '/api/public/mcp' | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/inspect'
    | '/api/chat'
    | '/api/public/mcp'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspectRoute: typeof InspectRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect': {
      id: '/inspect'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof InspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspectRoute: InspectRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
